name: Build and deploy frontend to Azure Web App - SPTIFRONT

on:
  push:
    branches:
      - feature/gym-management
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # 👇 Sube solo el resultado del build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build
          # Si usas Vite o Angular, cambia por ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5E230AD1659943CCAC95880CDF11D8CB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_48B6A9945637446986460BEFBBC56CE4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F37217666BF48988CE91C8B394A12A2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SPTIFRONT'
          package: './build'
